psblas3:
 config/pac.m4
 configure.ac
 configure

Added check for mpi_f08 module.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -7376,6 +7376,36 @@ else
  ac_exeext=''
 ac_ext='f90'
 ac_link='${MPIFC-$FC} -o conftest${ac_exeext} $FFLAGS $LDFLAGS conftest.$ac_ext $LIBS 1>&5'
+{ $as_echo "$as_me:$LINENO: checking MPI Fortran 2008 interface" >&5
+$as_echo_n "checking MPI Fortran 2008 interface... " >&6; }
+cat > conftest.$ac_ext <<EOF
+           program test
+             use mpi_f08
+           end program test
+EOF
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  $as_echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && test -s conftest${ac_exeext}; then
+  pac_cv_mpi_f08="yes";
+  { $as_echo "$as_me:$LINENO: result:  use mpi_f08. " >&5
+$as_echo " use mpi_f08. " >&6; }
+  :
+else
+  pac_cv_mpi_f08="no";
+  echo "configure: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+  { $as_echo "$as_me:$LINENO: result:  no. " >&5
+$as_echo " no. " >&6; }
+fi
+rm -f conftest*
+ if test x"$pac_cv_mpi_f08" == x"yes" ; then
+    FDEFINES="$psblas_cv_define_prepend-DMPI_MOD_F08 $FDEFINES";
+  else
+    ac_exeext=''
+ac_ext='f90'
+ac_link='${MPIFC-$FC} -o conftest${ac_exeext} $FFLAGS $LDFLAGS conftest.$ac_ext $LIBS 1>&5'
 { $as_echo "$as_me:$LINENO: checking MPI Fortran interface" >&5
 $as_echo_n "checking MPI Fortran interface... " >&6; }
 cat > conftest.$ac_ext <<EOF
@@ -7399,9 +7429,9 @@ else
 $as_echo " include mpif.h " >&6; }
   rm -rf conftest*
   FDEFINES="$psblas_cv_define_prepend-DMPI_H $FDEFINES"
-
 fi
 rm -f conftest*
+ fi
 fi
 
 
