psblas3: Fixed epstol into d_epstol. Added tests for same_type_as and extends_type_of

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -7704,6 +7704,94 @@ fi
 cd ..
 rm -fr tmpdir_$i
 
+ac_exeext=''
+ac_ext='f90'
+ac_link='${MPIFC-$FC} -o conftest${ac_exeext} $FCFLAGS $LDFLAGS conftest.$ac_ext $LIBS 1>&5'
+{ $as_echo "$as_me:$LINENO: checking support for Fortran SAME_TYPE_AS" >&5
+$as_echo_n "checking support for Fortran SAME_TYPE_AS... " >&6; }
+i=0
+while test \( -f tmpdir_$i \) -o \( -d tmpdir_$i \) ; do
+  i=`expr $i + 1`
+done
+mkdir tmpdir_$i
+cd tmpdir_$i
+cat > conftest.$ac_ext <<EOF
+program stt
+  type foo
+    integer :: i
+  end type foo
+  type, extends(foo) :: new_foo
+    integer :: j
+  end type new_foo
+  type(foo) :: foov
+  type(new_foo) :: nfv1, nfv2
+
+
+  write(*,*) 'foov == nfv1? ', same_type_as(foov,nfv1)
+  write(*,*) 'nfv2 == nfv1? ', same_type_as(nfv2,nfv1)
+end program stt
+EOF
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  $as_echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && test -s conftest${ac_exeext}; then
+  { $as_echo "$as_me:$LINENO: result: yes" >&5
+$as_echo "yes" >&6; }
+
+  FDEFINES="$psblas_cv_define_prepend-DHAVE_SAME_TYPE_AS $FDEFINES"
+else
+  { $as_echo "$as_me:$LINENO: result: no" >&5
+$as_echo "no" >&6; }
+  echo "configure: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+fi
+cd ..
+rm -fr tmpdir_$i
+
+ac_exeext=''
+ac_ext='f90'
+ac_link='${MPIFC-$FC} -o conftest${ac_exeext} $FCFLAGS $LDFLAGS conftest.$ac_ext $LIBS 1>&5'
+{ $as_echo "$as_me:$LINENO: checking support for Fortran EXTENDS_TYPE_OF" >&5
+$as_echo_n "checking support for Fortran EXTENDS_TYPE_OF... " >&6; }
+i=0
+while test \( -f tmpdir_$i \) -o \( -d tmpdir_$i \) ; do
+  i=`expr $i + 1`
+done
+mkdir tmpdir_$i
+cd tmpdir_$i
+cat > conftest.$ac_ext <<EOF
+program xtt
+  type foo
+    integer :: i
+  end type foo
+  type, extends(foo) :: new_foo
+    integer :: j
+  end type new_foo
+  type(foo) :: foov
+  type(new_foo) :: nfv1, nfv2
+
+  write(*,*) 'nfv1 extends foov? ', extends_type_of(nfv1,foov)
+end program xtt
+EOF
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  $as_echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && test -s conftest${ac_exeext}; then
+  { $as_echo "$as_me:$LINENO: result: yes" >&5
+$as_echo "yes" >&6; }
+
+  FDEFINES="$psblas_cv_define_prepend-DHAVE_EXTENDS_TYPE_OF $FDEFINES"
+else
+  { $as_echo "$as_me:$LINENO: result: no" >&5
+$as_echo "no" >&6; }
+  echo "configure: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+fi
+cd ..
+rm -fr tmpdir_$i
+
 ###############################################################################
 #	Additional pathname stuff (yes, it is redundant and confusing...)
 ###############################################################################
