psblas3:  base/comm/psb_dhalo.f90  base/comm/psb_dspgather.F90  base/comm/psb_shalo.f90  base/internals/psi_bld_g2lmap.f90  base/internals/psi_bld_tmphalo.f90  base/internals/psi_cswapdata.F90  base/internals/psi_cswaptran.F90  base/internals/psi_desc_index.F90  base/internals/psi_dl_check.f90  base/internals/psi_dswapdata.F90  base/internals/psi_dswaptran.F90  base/internals/psi_extrct_dl.F90  base/internals/psi_fnd_owner.F90  base/internals/psi_iswapdata.F90  base/internals/psi_iswaptran.F90  base/internals/psi_sswapdata.F90  base/internals/psi_sswaptran.F90  base/internals/psi_zswapdata.F90  base/internals/psi_zswaptran.F90  base/internals/srtlist.f  base/modules/psb_base_mat_mod.f03  base/modules/psb_c_tools_mod.f90  base/modules/psb_const_mod.F90  base/modules/psb_d_tools_mod.f90  base/modules/psb_desc_type.f90  base/modules/psb_error_impl.F90  base/modules/psb_error_mod.F90  base/modules/psb_gps_mod.f90  base/modules/psb_hash_mod.f90  base/modules/psb_realloc_mod.F90  base/modules/psb_s_tools_mod.f90  base/modules/psb_z_tools_mod.f90  base/modules/psi_comm_buffers_mod.F90  base/modules/psi_p2p_mod.F90  base/modules/psi_penv_mod.F90  base/psblas/psb_sxdot.f90  base/serial/aux/dasrx.f90  base/serial/aux/dmsr.f90  base/serial/aux/dmsrx.f90  base/serial/aux/zamsr.f90  base/serial/f03/psb_c_coo_impl.f03  base/serial/f03/psb_c_mat_impl.f03  base/serial/f03/psb_d_coo_impl.f03  base/serial/f03/psb_d_mat_impl.f03  base/serial/f03/psb_s_coo_impl.f03  base/serial/f03/psb_s_mat_impl.f03  base/serial/f03/psb_z_coo_impl.f03  base/serial/f03/psb_z_mat_impl.f03  base/serial/f77/smmp.f  base/serial/psb_cnumbmm.f90  base/serial/psb_crwextd.f90  base/serial/psb_csymbmm.f90  base/serial/psb_dnumbmm.f90  base/serial/psb_drwextd.f90  base/serial/psb_dsymbmm.f90  base/serial/psb_snumbmm.f90  base/serial/psb_sort_impl.f90  base/serial/psb_srwextd.f90  base/serial/psb_ssymbmm.f90  base/serial/psb_znumbmm.f90  base/serial/psb_zrwextd.f90  base/serial/psb_zsymbmm.f90  base/serial/psi_impl.f90  base/tools/psb_ccdbldext.F90  base/tools/psb_cd_inloc.f90  base/tools/psb_cd_set_bld.f90  base/tools/psb_cdins.f90  base/tools/psb_cspins.f90  base/tools/psb_dcdbldext.F90  base/tools/psb_dspins.f90  base/tools/psb_glob_to_loc.f90  base/tools/psb_linmap.f90  base/tools/psb_loc_to_glob.f90  base/tools/psb_map.f90  base/tools/psb_scdbldext.F90  base/tools/psb_sspins.f90  base/tools/psb_zcdbldext.F90  base/tools/psb_zspins.f90  config/pac.m4  configure.ac  configure  krylov/psb_base_inner_krylov_mod.f90  krylov/psb_ckrylov.f90  krylov/psb_dkrylov.f90  krylov/psb_skrylov.f90  krylov/psb_zkrylov.f90  prec/psb_c_bjacprec.f03  prec/psb_cilu_fct.f90  prec/psb_cprecinit.f90  prec/psb_d_bjacprec.f03  prec/psb_dilu_fct.f90  prec/psb_dprecinit.f90  prec/psb_prec_const_mod.f03  prec/psb_s_bjacprec.f03  prec/psb_silu_fct.f90  prec/psb_sprecinit.f90  prec/psb_z_bjacprec.f03  prec/psb_zilu_fct.f90  prec/psb_zprecinit.f90  test/fileread/cf_sample.f90  test/fileread/df_sample.f90  test/fileread/getp.f90  test/fileread/sf_sample.f90  test/fileread/zf_sample.f90  test/pargen/ppde.f90  test/pargen/spde.f90  test/serial/d_coo_matgen.f03  test/serial/d_matgen.f03  test/torture/psbtf.f90  util/psb_hbio_impl.f90  util/psb_mat_dist_impl.f90  util/psb_metispart_mod.F90  util/psb_mmio_impl.f90
I/O changes with ISO_FORTRAN_ENV psb_XXX_unit & friends.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -7659,6 +7659,34 @@ rm -fr tmpdir_$i
 
 ac_exeext=''
 ac_ext='f90'
+ac_link='${MPIFC-$FC} -o conftest${ac_exeext} $FFLAGS $LDFLAGS conftest.$ac_ext $LIBS 1>&5'
+{ $as_echo "$as_me:$LINENO: checking support for ISO_FORTRAN_ENV" >&5
+$as_echo_n "checking support for ISO_FORTRAN_ENV... " >&6; }
+cat > conftest.$ac_ext <<EOF
+           program test
+             use iso_fortran_env
+           end program test
+EOF
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  $as_echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && test -s conftest${ac_exeext}; then
+  { $as_echo "$as_me:$LINENO: result: yes" >&5
+$as_echo "yes" >&6; }
+  rm -rf conftest*
+  FDEFINES="$psblas_cv_define_prepend-DHAVE_ISO_FORTRAN_ENV $FDEFINES"
+else
+  echo "configure: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+  { $as_echo "$as_me:$LINENO: result: no" >&5
+$as_echo "no" >&6; }
+fi
+rm -f conftest*
+
+
+ac_exeext=''
+ac_ext='f90'
 ac_link='${MPIFC-$FC} -o conftest${ac_exeext} $FCFLAGS $LDFLAGS conftest.$ac_ext $LIBS 1>&5'
 { $as_echo "$as_me:$LINENO: checking support for Fortran FINAL" >&5
 $as_echo_n "checking support for Fortran FINAL... " >&6; }
