psblas3:  configure.ac  configure
Make FINAL a mandatory feature.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -7708,9 +7708,9 @@ $as_echo "no" >&6; }
 		     echo "configure: failed program was:" >&5
 		     cat conftest.$ac_ext >&5
 		      { { $as_echo "$as_me:$LINENO: error: Sorry, cannot build PSBLAS without support for TR15581.
- Please get a Fortran compiler that supports it, e.g. GNU Fortran 4.6." >&5
+ Please get a Fortran compiler that supports it, e.g. GNU Fortran 4.9." >&5
 $as_echo "$as_me: error: Sorry, cannot build PSBLAS without support for TR15581.
- Please get a Fortran compiler that supports it, e.g. GNU Fortran 4.6." >&2;}
+ Please get a Fortran compiler that supports it, e.g. GNU Fortran 4.9." >&2;}
    { (exit 1); exit 1; }; }
 
 fi
@@ -7779,9 +7779,9 @@ $as_echo "no" >&6; }
 		     echo "configure: failed program was:" >&5
 		     cat conftest.$ac_ext >&5
 		      { { $as_echo "$as_me:$LINENO: error: Sorry, cannot build PSBLAS without support for EXTENDS.
- Please get a Fortran compiler that supports it, e.g. GNU Fortran 4.6." >&5
+ Please get a Fortran compiler that supports it, e.g. GNU Fortran 4.9." >&5
 $as_echo "$as_me: error: Sorry, cannot build PSBLAS without support for EXTENDS.
- Please get a Fortran compiler that supports it, e.g. GNU Fortran 4.6." >&2;}
+ Please get a Fortran compiler that supports it, e.g. GNU Fortran 4.9." >&2;}
    { (exit 1); exit 1; }; }
 
 fi
@@ -7866,9 +7866,9 @@ $as_echo "no" >&6; }
 		     echo "configure: failed program was:" >&5
 		     cat conftest.$ac_ext >&5
 		      { { $as_echo "$as_me:$LINENO: error: Sorry, cannot build PSBLAS without support for CLASS and type bound procedures.
- Please get a Fortran compiler that supports them, e.g. GNU Fortran 4.6." >&5
+ Please get a Fortran compiler that supports them, e.g. GNU Fortran 4.9." >&5
 $as_echo "$as_me: error: Sorry, cannot build PSBLAS without support for CLASS and type bound procedures.
- Please get a Fortran compiler that supports them, e.g. GNU Fortran 4.6." >&2;}
+ Please get a Fortran compiler that supports them, e.g. GNU Fortran 4.9." >&2;}
    { (exit 1); exit 1; }; }
 
 fi
@@ -7939,9 +7939,9 @@ $as_echo "no" >&6; }
 		     echo "configure: failed program was:" >&5
 		     cat conftest.$ac_ext >&5
 		      { { $as_echo "$as_me:$LINENO: error: Sorry, cannot build PSBLAS without support for SOURCE= allocation.
- Please get a Fortran compiler that supports it, e.g. GNU Fortran 4.6." >&5
+ Please get a Fortran compiler that supports it, e.g. GNU Fortran 4.9." >&5
 $as_echo "$as_me: error: Sorry, cannot build PSBLAS without support for SOURCE= allocation.
- Please get a Fortran compiler that supports it, e.g. GNU Fortran 4.6." >&2;}
+ Please get a Fortran compiler that supports it, e.g. GNU Fortran 4.9." >&2;}
    { (exit 1); exit 1; }; }
 
 fi
@@ -8002,9 +8002,9 @@ $as_echo "no" >&6; }
 		     echo "configure: failed program was:" >&5
 		     cat conftest.$ac_ext >&5
 		      { { $as_echo "$as_me:$LINENO: error: Sorry, cannot build PSBLAS without support for MOVE_ALLOC.
- Please get a Fortran compiler that supports it, e.g. GNU Fortran 4.6." >&5
+ Please get a Fortran compiler that supports it, e.g. GNU Fortran 4.9." >&5
 $as_echo "$as_me: error: Sorry, cannot build PSBLAS without support for MOVE_ALLOC.
- Please get a Fortran compiler that supports it, e.g. GNU Fortran 4.6." >&2;}
+ Please get a Fortran compiler that supports it, e.g. GNU Fortran 4.9." >&2;}
    { (exit 1); exit 1; }; }
 
 fi
@@ -8064,9 +8064,85 @@ $as_echo "no" >&6; }
 		     echo "configure: failed program was:" >&5
 		     cat conftest.$ac_ext >&5
 		      { { $as_echo "$as_me:$LINENO: error: Sorry, cannot build PSBLAS without support for ISO_C_BINDING.
- Please get a Fortran compiler that supports it, e.g. GNU Fortran 4.6." >&5
+ Please get a Fortran compiler that supports it, e.g. GNU Fortran 4.9." >&5
 $as_echo "$as_me: error: Sorry, cannot build PSBLAS without support for ISO_C_BINDING.
- Please get a Fortran compiler that supports it, e.g. GNU Fortran 4.6." >&2;}
+ Please get a Fortran compiler that supports it, e.g. GNU Fortran 4.9." >&2;}
+   { (exit 1); exit 1; }; }
+
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+ac_ext=c
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_c_compiler_gnu
+
+
+{ $as_echo "$as_me:$LINENO: checking support for Fortran FINAL" >&5
+$as_echo_n "checking support for Fortran FINAL... " >&6; }
+ ac_ext=${ac_fc_srcext-f}
+ac_compile='$FC -c $FCFLAGS $ac_fcflags_srcext conftest.$ac_ext >&5'
+ac_link='$FC -o conftest$ac_exeext $FCFLAGS $LDFLAGS $ac_fcflags_srcext conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_fc_compiler_gnu
+
+ ac_exeext=''
+ ac_ext='f90'
+  ac_fc=${MPIFC-$FC};
+ cat >conftest.$ac_ext <<_ACEOF
+
+module conftest_mod
+  type foo
+    integer :: i
+  contains
+    final  :: destroy_foo
+  end type foo
+
+  private destroy_foo
+contains
+  subroutine destroy_foo(a)
+    type(foo) :: a
+     ! Just a test
+  end subroutine destroy_foo
+end module conftest_mod
+program conftest
+  use conftest_mod
+  type(foo) :: foovar
+end program conftest
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval ac_try_echo="\"\$as_me:$LINENO: $ac_try_echo\""
+$as_echo "$ac_try_echo") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  $as_echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_fc_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+    { $as_echo "$as_me:$LINENO: result: yes" >&5
+$as_echo "yes" >&6; }
+		      FDEFINES="$psblas_cv_define_prepend-DHAVE_FINAL $FDEFINES"
+else
+  $as_echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	  { $as_echo "$as_me:$LINENO: result: no" >&5
+$as_echo "no" >&6; }
+		     echo "configure: failed program was:" >&5
+		     cat conftest.$ac_ext >&5
+		      { { $as_echo "$as_me:$LINENO: error: Sorry, cannot build PSBLAS without support for ISO_C_BINDING.
+ Please get a Fortran compiler that supports it, e.g. GNU Fortran 4.9." >&5
+$as_echo "$as_me: error: Sorry, cannot build PSBLAS without support for ISO_C_BINDING.
+ Please get a Fortran compiler that supports it, e.g. GNU Fortran 4.9." >&2;}
    { (exit 1); exit 1; }; }
 
 fi
@@ -8325,77 +8401,6 @@ ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
 ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
 ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
-
-
-{ $as_echo "$as_me:$LINENO: checking support for Fortran FINAL" >&5
-$as_echo_n "checking support for Fortran FINAL... " >&6; }
- ac_ext=${ac_fc_srcext-f}
-ac_compile='$FC -c $FCFLAGS $ac_fcflags_srcext conftest.$ac_ext >&5'
-ac_link='$FC -o conftest$ac_exeext $FCFLAGS $LDFLAGS $ac_fcflags_srcext conftest.$ac_ext $LIBS >&5'
-ac_compiler_gnu=$ac_cv_fc_compiler_gnu
-
- ac_exeext=''
- ac_ext='f90'
-  ac_fc=${MPIFC-$FC};
- cat >conftest.$ac_ext <<_ACEOF
-
-module conftest_mod
-  type foo
-    integer :: i
-  contains
-    final  :: destroy_foo
-  end type foo
-
-  private destroy_foo
-contains
-  subroutine destroy_foo(a)
-    type(foo) :: a
-     ! Just a test
-  end subroutine destroy_foo
-end module conftest_mod
-program conftest
-  use conftest_mod
-  type(foo) :: foovar
-end program conftest
-_ACEOF
-rm -f conftest.$ac_objext
-if { (ac_try="$ac_compile"
-case "(($ac_try" in
-  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
-  *) ac_try_echo=$ac_try;;
-esac
-eval ac_try_echo="\"\$as_me:$LINENO: $ac_try_echo\""
-$as_echo "$ac_try_echo") >&5
-  (eval "$ac_compile") 2>conftest.er1
-  ac_status=$?
-  grep -v '^ *+' conftest.er1 >conftest.err
-  rm -f conftest.er1
-  cat conftest.err >&5
-  $as_echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } && {
-	 test -z "$ac_fc_werror_flag" ||
-	 test ! -s conftest.err
-       } && test -s conftest.$ac_objext; then
-    { $as_echo "$as_me:$LINENO: result: yes" >&5
-$as_echo "yes" >&6; }
-		      FDEFINES="$psblas_cv_define_prepend-DHAVE_FINAL $FDEFINES"
-else
-  $as_echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
-	  { $as_echo "$as_me:$LINENO: result: no" >&5
-$as_echo "no" >&6; }
-		     echo "configure: failed program was:" >&5
-		     cat conftest.$ac_ext >&5
-
-fi
-
-rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
-ac_ext=c
-ac_cpp='$CPP $CPPFLAGS'
-ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
-ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
-ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
 
 
